services:
  api:
    image: atc-challenge:dev
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      ATC_BASE_URL: http://mock:4000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SLOTS_TTL: 300
      DEFAULT_TTL: 3600
    depends_on:
      - redis
  mock:
    image: atc-challenge:dev
    command: node /usr/src/app/mock/server.js
    volumes:
      - ./mock:/usr/src/app/mock
    ports:
      - 4000:4000
    environment:
      EVENT_INTERVAL_SECONDS: 10
      REQUESTS_PER_MINUTE: 60
      EVENT_PUBLISHER_URL: http://api:3000/events
  # Redis Service
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - default
    restart: always
